test_cost_file_service.py:3: in <module>
    from app import app
..\..\app.py:13: in <module>
    from api.experiment_resource import ExperimentResource, ExperimentsResource, RefreshExperimentsResource
..\..\api\experiment_resource.py:5: in <module>
    from services import experiment_service, notification_service
..\..\services\experiment_service.py:9: in <module>
    from models.experiment_master import ExperimentMaster, experiments_schema, experiment_schema    
..\..\models\__init__.py:1: in <module>
    from .access_groups import AccessGroups
..\..\models\access_groups.py:4: in <module>
    from .base import Base
..\..\models\base.py:9: in <module>
    engine = get_db_engine()
..\..\configs.py:137: in get_db_engine
    return get_ltvo_utils_prod_dev_db_engine()
..\..\configs.py:211: in get_ltvo_utils_prod_dev_db_engine
    client = secretmanager.SecretManagerServiceClient()
C:\Users\10722751\AppData\Local\Programs\Python\Python311\Lib\site-packages\google\cloud\secretmanager_v1\services\secret_manager_service\client.py:481: in __init__
    self._transport = Transport(
C:\Users\10722751\AppData\Local\Programs\Python\Python311\Lib\site-packages\google\cloud\secretmanager_v1\services\secret_manager_service\transports\grpc.py:157: in __init__
    super().__init__(
C:\Users\10722751\AppData\Local\Programs\Python\Python311\Lib\site-packages\google\cloud\secretmanager_v1\services\secret_manager_service\transports\base.py:100: in __init__
    credentials, _ = google.auth.default(
C:\Users\10722751\AppData\Local\Programs\Python\Python311\Lib\site-packages\google\auth\_default.py:691: in default
    raise exceptions.DefaultCredentialsError(_CLOUD_SDK_MISSING_CREDENTIALS)
E   google.auth.exceptions.DefaultCredentialsError: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
